import fs from "fs";
import path from "path";

const CREATE_NAME__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE = "CreateWhitelist";
const CREATE__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./create.graphql"), {
	encoding: "utf8",
});
const READ_NAME__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE = "ReadWhitelist";
const READ__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./read.graphql"), {
	encoding: "utf8",
});
const UPDATE_NAME__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE = "UpdateWhitelist";
const UPDATE__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./update.graphql"), {
	encoding: "utf8",
});
const DELETE_NAME__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE = "DeleteWhitelist";
const DELETE__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./delete.graphql"), {
	encoding: "utf8",
});

export {
	CREATE_NAME__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	CREATE__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	READ_NAME__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	READ__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	UPDATE_NAME__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	UPDATE__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	DELETE_NAME__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	DELETE__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE,
};
