import fs from "fs";
import path from "path";

const CREATE_NAME__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE = "CreateWhitelist";
const CREATE__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./create.graphql"), {
	encoding: "utf8",
});
const READ_NAME__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE = "ReadWhitelist";
const READ__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./read.graphql"), {
	encoding: "utf8",
});
const CURSOR_READ_NAME__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE = "CursorReadWhitelist";
const CURSOR_READ__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./cursor_read.graphql"), {
	encoding: "utf8",
});
const UPDATE_NAME__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE = "UpdateWhitelist";
const UPDATE__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./update.graphql"), {
	encoding: "utf8",
});
const CURSOR_UPDATE_NAME__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE = "CursorUpdateWhitelist";
const CURSOR_UPDATE__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./cursor_update.graphql"), {
	encoding: "utf8",
});
const DELETE_NAME__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE = "DeleteWhitelist";
const DELETE__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./delete.graphql"), {
	encoding: "utf8",
});
const CURSOR_DELETE_NAME__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE = "CursorDeleteWhitelist";
const CURSOR_DELETE__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./cursor_delete.graphql"), {
	encoding: "utf8",
});
const COUNT_NAME__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE = "CountWhitelist";
const COUNT__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./count.graphql"), {
	encoding: "utf8",
});

export {
	CREATE_NAME__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	CREATE__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	READ_NAME__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	READ__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	CURSOR_READ_NAME__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	CURSOR_READ__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	UPDATE_NAME__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	UPDATE__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	CURSOR_UPDATE_NAME__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	CURSOR_UPDATE__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	DELETE_NAME__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	DELETE__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	CURSOR_DELETE_NAME__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	CURSOR_DELETE__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	COUNT_NAME__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	COUNT__WHITELIST__OPERATION__GRAPHQL__INTERFACE__DATABASE,
};
