import {
	SystemModelSystemController,
	RootSystemModelSystemController
} from './common.js'
import {
	ENTITY1_SYSTEM_MODEL
} from './../models/entity1.js'

const ENTITY1_SYSTEM_CONTROLLER_CONFIG = {}
const ENTITY1_SYSTEM_CONTROLLER = new SystemModelSystemController(ENTITY1_SYSTEM_CONTROLLER_CONFIG, ENTITY1_SYSTEM_MODEL)

const ROOT_ENTITY1_SYSTEM_CONTROLLER_CONFIG = {}
const ROOT_ENTITY1_SYSTEM_CONTROLLER = new RootSystemModelSystemController(ROOT_ENTITY1_SYSTEM_CONTROLLER_CONFIG, ENTITY1_SYSTEM_MODEL)

export {
	ENTITY1_SYSTEM_CONTROLLER,
	ROOT_ENTITY1_SYSTEM_CONTROLLER
}