import * as $kernel from "./../../kernel/index.js";

import { RELATIONSHIP_MODEL_SYSTEM } from "./../models/relationship.js";

const RELATIONSHIP_CONTROLLER_ROOT_CONFIG = {};
const RELATIONSHIP_CONTROLLER_SYSTEM_CONFIG = {
	model: RELATIONSHIP_MODEL_SYSTEM,
	model_name: "RELATIONSHIP_MODEL_SYSTEM",
};
const RELATIONSHIP_CONTROLLER_SYSTEM = new $kernel.controllers.system.SystemController(RELATIONSHIP_CONTROLLER_ROOT_CONFIG, RELATIONSHIP_CONTROLLER_SYSTEM_CONFIG);

export { RELATIONSHIP_CONTROLLER_SYSTEM };
