mutation DeleteNestedMutation {
  update_entity1(where: {id: "1"}, attributes: {text: "123"}) {
    attributes {
      id
      text
    }
    mutation {
      delete_entity2(where: {id: "2"}) {
        attributes {
          id
          text
        }
      }
    }
  }
}
