mutation UpdateNestedMutation {
  update_entity1(where: {id: "1"}, attributes: { text: "123" }) {
    attributes {
      id
      text
    }
    mutation {
      update_entity2(where: {id: "2"}, attributes: { text: "456"}) {
        attributes {
          id
          text
        }
      }
    }
  }
}
