import fs from "fs";
import path from "path";

const CREATE_NAME__SESSION__OPERATION__GRAPHQL__INTERFACE__DATABASE = "CreateSession";
const CREATE__SESSION__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./create.graphql"), {
	encoding: "utf8",
});
const READ_NAME__SESSION__OPERATION__GRAPHQL__INTERFACE__DATABASE = "ReadSession";
const READ__SESSION__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./read.graphql"), {
	encoding: "utf8",
});
const UPDATE_NAME__SESSION__OPERATION__GRAPHQL__INTERFACE__DATABASE = "UpdateSession";
const UPDATE__SESSION__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./update.graphql"), {
	encoding: "utf8",
});
const DELETE_NAME__SESSION__OPERATION__GRAPHQL__INTERFACE__DATABASE = "DeleteSession";
const DELETE__SESSION__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./delete.graphql"), {
	encoding: "utf8",
});
const COUNT_NAME__SESSION__OPERATION__GRAPHQL__INTERFACE__DATABASE = "CountSession";
const COUNT__SESSION__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./count.graphql"), {
	encoding: "utf8",
});

export {
	CREATE_NAME__SESSION__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	CREATE__SESSION__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	READ_NAME__SESSION__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	READ__SESSION__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	UPDATE_NAME__SESSION__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	UPDATE__SESSION__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	DELETE_NAME__SESSION__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	DELETE__SESSION__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	COUNT_NAME__SESSION__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	COUNT__SESSION__OPERATION__GRAPHQL__INTERFACE__DATABASE,
};
