import fs from "fs";
import path from "path";

const CREATE_NAME__YTITNE__OPERATION__GRAPHQL__INTERFACE__DATABASE = "CreateYtitne";
const CREATE__YTITNE__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./create.graphql"), {
	encoding: "utf8",
});
const READ_NAME__YTITNE__OPERATION__GRAPHQL__INTERFACE__DATABASE = "ReadYtitne";
const READ__YTITNE__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./read.graphql"), {
	encoding: "utf8",
});
const UPDATE_NAME__YTITNE__OPERATION__GRAPHQL__INTERFACE__DATABASE = "UpdateYtitne";
const UPDATE__YTITNE__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./update.graphql"), {
	encoding: "utf8",
});
const DELETE_NAME__YTITNE__OPERATION__GRAPHQL__INTERFACE__DATABASE = "DeleteYtitne";
const DELETE__YTITNE__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./delete.graphql"), {
	encoding: "utf8",
});

export {
	CREATE_NAME__YTITNE__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	CREATE__YTITNE__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	READ_NAME__YTITNE__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	READ__YTITNE__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	UPDATE_NAME__YTITNE__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	UPDATE__YTITNE__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	DELETE_NAME__YTITNE__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	DELETE__YTITNE__OPERATION__GRAPHQL__INTERFACE__DATABASE,
};
