// relationships are defined using the graphql type constant

const DATABASE__RELATIONSHIP__STRUCTURE = {};

const SYSTEM__RELATIONSHIP__STRUCTURE = DATABASE__RELATIONSHIP__STRUCTURE;

export { DATABASE__RELATIONSHIP__STRUCTURE, SYSTEM__RELATIONSHIP__STRUCTURE };
