// relationships are defined using the graphql type constant

import { TYPE__GRAPHQL__DATABASE__ENTITY1__STRUCTURE } from "./entity1/database/graphql.js";
import { TYPE__GRAPHQL__DATABASE__ENTITY2__STRUCTURE } from "./entity2/database/graphql.js";

const DATABASE_RELATIONSHIP_STRUCTURE = {
	[TYPE__GRAPHQL__DATABASE__ENTITY1__STRUCTURE]: [TYPE__GRAPHQL__DATABASE__ENTITY2__STRUCTURE],
	[TYPE__GRAPHQL__DATABASE__ENTITY2__STRUCTURE]: [TYPE__GRAPHQL__DATABASE__ENTITY1__STRUCTURE],
};

const SYSTEM_RELATIONSHIP_STRUCTURE = DATABASE_RELATIONSHIP_STRUCTURE;

export { DATABASE_RELATIONSHIP_STRUCTURE, SYSTEM_RELATIONSHIP_STRUCTURE };
