import fs from "fs";
import path from "path";

const CREATE_NAME__BLACKLIST__OPERATION__GRAPHQL__INTERFACE__DATABASE = "CreateBlacklist";
const CREATE__BLACKLIST__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./create.graphql"), {
	encoding: "utf8",
});
const READ_NAME__BLACKLIST__OPERATION__GRAPHQL__INTERFACE__DATABASE = "ReadBlacklist";
const READ__BLACKLIST__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./read.graphql"), {
	encoding: "utf8",
});
const UPDATE_NAME__BLACKLIST__OPERATION__GRAPHQL__INTERFACE__DATABASE = "UpdateBlacklist";
const UPDATE__BLACKLIST__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./update.graphql"), {
	encoding: "utf8",
});
const DELETE_NAME__BLACKLIST__OPERATION__GRAPHQL__INTERFACE__DATABASE = "DeleteBlacklist";
const DELETE__BLACKLIST__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./delete.graphql"), {
	encoding: "utf8",
});
const COUNT_NAME__BLACKLIST__OPERATION__GRAPHQL__INTERFACE__DATABASE = "CountBlacklist";
const COUNT__BLACKLIST__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./count.graphql"), {
	encoding: "utf8",
});

export {
	CREATE_NAME__BLACKLIST__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	CREATE__BLACKLIST__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	READ_NAME__BLACKLIST__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	READ__BLACKLIST__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	UPDATE_NAME__BLACKLIST__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	UPDATE__BLACKLIST__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	DELETE_NAME__BLACKLIST__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	DELETE__BLACKLIST__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	COUNT_NAME__BLACKLIST__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	COUNT__BLACKLIST__OPERATION__GRAPHQL__INTERFACE__DATABASE,
};
