// relationships are defined using the graphql type constant

// ytitne
import { TYPE__GRAPHQL__DATABASE__YTITNE__STRUCTURE } from "./entities/ytitne/database/graphql.js";

const DATABASE__RELATIONSHIP__STRUCTURE = {
	[TYPE__GRAPHQL__DATABASE__YTITNE__STRUCTURE]: [TYPE__GRAPHQL__DATABASE__YTITNE__STRUCTURE],
};

const SYSTEM__RELATIONSHIP__STRUCTURE = DATABASE__RELATIONSHIP__STRUCTURE;

export { DATABASE__RELATIONSHIP__STRUCTURE, SYSTEM__RELATIONSHIP__STRUCTURE };
