// relationships are defined using the graphql type constant

// ytitne
import { TYPE__GRAPHQL__DATABASE__YTITNE__STRUCTURE } from "./entities/ytitne/database/graphql.js";

/*
	ytitne <-> ytitne
*/
const DATABASE_RELATIONSHIPS__RELATIONSHIP__STRUCTURE = {
	[TYPE__GRAPHQL__DATABASE__YTITNE__STRUCTURE]: [TYPE__GRAPHQL__DATABASE__YTITNE__STRUCTURE],
};

const SYSTEM_RELATIONSHIPS__RELATIONSHIP__STRUCTURE = DATABASE_RELATIONSHIPS__RELATIONSHIP__STRUCTURE;

export { DATABASE_RELATIONSHIPS__RELATIONSHIP__STRUCTURE, SYSTEM_RELATIONSHIPS__RELATIONSHIP__STRUCTURE };
