// relationships are defined using the graphql type constant

const DATABASE_RELATIONSHIPS__RELATIONSHIP__STRUCTURE = {};

const SYSTEM_RELATIONSHIPS__RELATIONSHIP__STRUCTURE = DATABASE_RELATIONSHIPS__RELATIONSHIP__STRUCTURE;

export { DATABASE_RELATIONSHIPS__RELATIONSHIP__STRUCTURE, SYSTEM_RELATIONSHIPS__RELATIONSHIP__STRUCTURE };
