import fs from 'fs'
import path from 'path'

const ENTITY2_CREATE_OPERATION_NAME_GRAPHQL_INTERFACE_DATABASE = 'CreateEntity2'
const ENTITY2_CREATE_OPERATION_GRAPHQL_INTERFACE_DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, './create.graphql'), {
	encoding: 'utf8'
})
const ENTITY2_READ_OPERATION_NAME_GRAPHQL_INTERFACE_DATABASE = 'ReadEntity2'
const ENTITY2_READ_OPERATION_GRAPHQL_INTERFACE_DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, './read.graphql'), {
	encoding: 'utf8'
})
const ENTITY2_UPDATE_OPERATION_NAME_GRAPHQL_INTERFACE_DATABASE = 'UpdateEntity2'
const ENTITY2_UPDATE_OPERATION_GRAPHQL_INTERFACE_DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, './update.graphql'), {
	encoding: 'utf8'
})
const ENTITY2_DELETE_OPERATION_NAME_GRAPHQL_INTERFACE_DATABASE = 'DeleteEntity2'
const ENTITY2_DELETE_OPERATION_GRAPHQL_INTERFACE_DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, './delete.graphql'), {
	encoding: 'utf8'
})

export {
	ENTITY2_CREATE_OPERATION_NAME_GRAPHQL_INTERFACE_DATABASE,
	ENTITY2_CREATE_OPERATION_GRAPHQL_INTERFACE_DATABASE,
	ENTITY2_READ_OPERATION_NAME_GRAPHQL_INTERFACE_DATABASE,
	ENTITY2_READ_OPERATION_GRAPHQL_INTERFACE_DATABASE,
	ENTITY2_UPDATE_OPERATION_NAME_GRAPHQL_INTERFACE_DATABASE,
	ENTITY2_UPDATE_OPERATION_GRAPHQL_INTERFACE_DATABASE,
	ENTITY2_DELETE_OPERATION_NAME_GRAPHQL_INTERFACE_DATABASE,
	ENTITY2_DELETE_OPERATION_GRAPHQL_INTERFACE_DATABASE
}