export default function ($abstract) {
	const ENTITY = {
		name: "gauze__relationship",
		primary_key: "gauze__relationship__id",
		fields: {
			gauze__relationship__id: {
				name: "gauze__relationship__id",
				sql_type: "uuid",
				graphql_type: $abstract.gauze.types.graphql.STRING__GRAPHQL__TYPE__GAUZE__ABSTRACT,
				description: "id",
				pre_serialize_middlewares: [$abstract.gauze.middlewares.ID_PROTECTED__MIDDLEWARES__GAUZE__ABSTRACT],
				serializers: [],
				post_serialize_middlewares: [],
				pre_deserialize_middlewares: [],
				deserializers: [],
				post_deserialize_middlewares: [],
			},
			gauze__relationship__created_at: {
				name: "gauze__relationship__created_at",
				sql_type: "datetime",
				graphql_type: $abstract.gauze.types.graphql.DATE__GRAPHQL__TYPE__GAUZE__ABSTRACT,
				description: "created_at",
				pre_serialize_middlewares: [$abstract.gauze.middlewares.CREATED_AT_PROTECTED__MIDDLEWARES__GAUZE__ABSTRACT],
				serializers: [$abstract.gauze.serializers.CREATED_AT__SERIALIZERS__GAUZE__ABSTRACT],
				post_serialize_middlewares: [],
				pre_deserialize_middlewares: [],
				deserializers: [$abstract.gauze.deserializers.CREATED_AT__DESERIALIZERS__GAUZE__ABSTRACT],
				post_deserialize_middlewares: [],
			},
			gauze__relationship__updated_at: {
				name: "gauze__relationship__updated_at",
				sql_type: "datetime",
				graphql_type: $abstract.gauze.types.graphql.DATE__GRAPHQL__TYPE__GAUZE__ABSTRACT,
				description: "updated_at",
				pre_serialize_middlewares: [$abstract.gauze.middlewares.UPDATED_AT_PROTECTED__MIDDLEWARES__GAUZE__ABSTRACT],
				serializers: [$abstract.gauze.serializers.UPDATED_AT__SERIALIZERS__GAUZE__ABSTRACT],
				post_serialize_middlewares: [],
				pre_deserialize_middlewares: [],
				deserializers: [$abstract.gauze.deserializers.UPDATED_AT__DESERIALIZERS__GAUZE__ABSTRACT],
				post_deserialize_middlewares: [],
			},
			gauze__relationship__deleted_at: {
				name: "gauze__relationship__deleted_at",
				sql_type: "datetime",
				graphql_type: $abstract.gauze.types.graphql.DATE__GRAPHQL__TYPE__GAUZE__ABSTRACT,
				description: "deleted_at",
				pre_serialize_middlewares: [$abstract.gauze.middlewares.DELETED_AT_PROTECTED__MIDDLEWARES__GAUZE__ABSTRACT],
				serializers: [$abstract.gauze.serializers.DELETED_AT__SERIALIZERS__GAUZE__ABSTRACT],
				post_serialize_middlewares: [],
				pre_deserialize_middlewares: [],
				deserializers: [$abstract.gauze.deserializers.DELETED_AT__DESERIALIZERS__GAUZE__ABSTRACT],
				post_deserialize_middlewares: [],
			},
			gauze__relationship__from_type: {
				name: "gauze__relationship__from_type",
				sql_type: "string",
				graphql_type: $abstract.gauze.types.graphql.STRING__GRAPHQL__TYPE__GAUZE__ABSTRACT,
				description: "from_type",
				pre_serialize_middlewares: [],
				serializers: [],
				post_serialize_middlewares: [],
				pre_deserialize_middlewares: [],
				deserializers: [],
				post_deserialize_middlewares: [],
			},
			gauze__relationship__from_id: {
				name: "gauze__relationship__from_id",
				sql_type: "uuid",
				graphql_type: $abstract.gauze.types.graphql.STRING__GRAPHQL__TYPE__GAUZE__ABSTRACT,
				description: "from_id",
				pre_serialize_middlewares: [],
				serializers: [],
				post_serialize_middlewares: [],
				pre_deserialize_middlewares: [],
				deserializers: [],
				post_deserialize_middlewares: [],
			},
			gauze__relationship__to_type: {
				name: "gauze__relationship__to_type",
				sql_type: "string",
				graphql_type: $abstract.gauze.types.graphql.STRING__GRAPHQL__TYPE__GAUZE__ABSTRACT,
				description: "to_type",
				pre_serialize_middlewares: [],
				serializers: [],
				post_serialize_middlewares: [],
				pre_deserialize_middlewares: [],
				deserializers: [],
				post_deserialize_middlewares: [],
			},
			gauze__relationship__to_id: {
				name: "gauze__relationship__to_id",
				sql_type: "uuid",
				graphql_type: $abstract.gauze.types.graphql.STRING__GRAPHQL__TYPE__GAUZE__ABSTRACT,
				description: "to_id",
				pre_serialize_middlewares: [],
				serializers: [],
				post_serialize_middlewares: [],
				pre_deserialize_middlewares: [],
				deserializers: [],
				post_deserialize_middlewares: [],
			},
		},
	};
	ENTITY.graphql_fields = $abstract.helpers.create_graphql_fields(ENTITY);
	ENTITY.graphql_attributes_string = $abstract.helpers.create_graphql_attributes_string(ENTITY);
	return ENTITY;
}
