import {
	SERIALIZER_CREATED_AT_STRUCTURE,
	SERIALIZER_UPDATED_AT_STRUCTURE,
	SERIALIZER_DELETED_AT_STRUCTURE
} from './../../serializers.js'

const SQL_DATABASE_ENTITY1_TABLE_NAME = 'gauze__entity1'
const SQL_DATABASE_ENTITY1_PRIMARY_KEY = 'id'
const SQL_DATABASE_ENTITY1_FIELDS = {
	id: true,
	created_at: true,
	updated_at: true,
	deleted_at: true,
	text: true
}
const SQL_DATABASE_ENTITY1_PROTECTED_FIELDS = ['id', 'created_at', 'updated_at', 'deleted_at']
const SQL_DATABASE_ENTITY1_FIELD_SERIALIZERS = {
	created_at: SERIALIZER_CREATED_AT_STRUCTURE,
	updated_at: SERIALIZER_UPDATED_AT_STRUCTURE,
	deleted_at: SERIALIZER_DELETED_AT_STRUCTURE
}

export {
	SQL_DATABASE_ENTITY1_TABLE_NAME,
	SQL_DATABASE_ENTITY1_PRIMARY_KEY,
	SQL_DATABASE_ENTITY1_FIELDS,
	SQL_DATABASE_ENTITY1_PROTECTED_FIELDS,
	SQL_DATABASE_ENTITY1_FIELD_SERIALIZERS
}