import * as $structure from "./../../../../structure/index.js";

import { READ__ENTITY2__QUERY__GRAPHQL__INTERFACE__DATABASE } from "./../queries/entity2.js";
import {
	CREATE__ENTITY2__MUTATION__GRAPHQL__INTERFACE__DATABASE,
	UPDATE__ENTITY2__MUTATION__GRAPHQL__INTERFACE__DATABASE,
	DELETE__ENTITY2__MUTATION__GRAPHQL__INTERFACE__DATABASE,
} from "./../mutations/entity2.js";

const CONNECTION__ENTITY2__ENTITY__GRAPHQL__INTERFACE__DATABASE = {
	query_relationships: $structure.entity2.database.graphql.QUERY_RELATIONSHIPS_FIELDS__GRAPHQL__DATABASE__ENTITY2__STRUCTURE,
	mutation_relationships: $structure.entity2.database.graphql.MUTATION_RELATIONSHIPS_FIELDS__GRAPHQL__DATABASE__ENTITY2__STRUCTURE,
	query_query: $structure.entity2.database.graphql.QUERY_QUERY_FIELDS__GRAPHQL__DATABASE__ENTITY2__STRUCTURE,
	mutation_mutation: $structure.entity2.database.graphql.MUTATION_MUTATION_FIELDS__GRAPHQL__DATABASE__ENTITY2__STRUCTURE,
};

const METHODS__ENTITY2__ENTITY__GRAPHQL__INTERFACE__DATABASE = {
	query: {
		read_entity2: READ__ENTITY2__QUERY__GRAPHQL__INTERFACE__DATABASE,
	},
	mutation: {
		create_entity2: CREATE__ENTITY2__MUTATION__GRAPHQL__INTERFACE__DATABASE,
		update_entity2: UPDATE__ENTITY2__MUTATION__GRAPHQL__INTERFACE__DATABASE,
		delete_entity2: DELETE__ENTITY2__MUTATION__GRAPHQL__INTERFACE__DATABASE,
	},
};

export { CONNECTION__ENTITY2__ENTITY__GRAPHQL__INTERFACE__DATABASE, METHODS__ENTITY2__ENTITY__GRAPHQL__INTERFACE__DATABASE };
