import * as $structure from "./../../../../structure/index.js";

import { READ__ENTITY1__QUERY__GRAPHQL__INTERFACE__DATABASE } from "./../queries/entity1.js";
import {
	CREATE__ENTITY1__MUTATION__GRAPHQL__INTERFACE__DATABASE,
	UPDATE__ENTITY1__MUTATION__GRAPHQL__INTERFACE__DATABASE,
	DELETE__ENTITY1__MUTATION__GRAPHQL__INTERFACE__DATABASE,
} from "./../mutations/entity1.js";

const CONNECTION__ENTITY1__ENTITY__GRAPHQL__INTERFACE__DATABASE = {
	query_relationships: $structure.entity1.database.graphql.QUERY_RELATIONSHIPS_FIELDS__GRAPHQL__DATABASE__ENTITY1__STRUCTURE,
	mutation_relationships: $structure.entity1.database.graphql.MUTATION_RELATIONSHIPS_FIELDS__GRAPHQL__DATABASE__ENTITY1__STRUCTURE,
	query_query: $structure.entity1.database.graphql.QUERY_QUERY_FIELDS__GRAPHQL__DATABASE__ENTITY1__STRUCTURE,
	mutation_mutation: $structure.entity1.database.graphql.MUTATION_MUTATION_FIELDS__GRAPHQL__DATABASE__ENTITY1__STRUCTURE,
};

const METHODS__ENTITY1__ENTITY__GRAPHQL__INTERFACE__DATABASE = {
	query: {
		read_entity1: READ__ENTITY1__QUERY__GRAPHQL__INTERFACE__DATABASE,
	},
	mutation: {
		create_entity1: CREATE__ENTITY1__MUTATION__GRAPHQL__INTERFACE__DATABASE,
		update_entity1: UPDATE__ENTITY1__MUTATION__GRAPHQL__INTERFACE__DATABASE,
		delete_entity1: DELETE__ENTITY1__MUTATION__GRAPHQL__INTERFACE__DATABASE,
	},
};

export { CONNECTION__ENTITY1__ENTITY__GRAPHQL__INTERFACE__DATABASE, METHODS__ENTITY1__ENTITY__GRAPHQL__INTERFACE__DATABASE };
