import * as $structure from "./../../../../structure/index.js";

import { READ__RELATIONSHIP__QUERY__GRAPHQL__INTERFACE__DATABASE, COUNT__RELATIONSHIP__QUERY__GRAPHQL__INTERFACE__DATABASE } from "./../queries/relationship.js";
import {
	CREATE__RELATIONSHIP__MUTATION__GRAPHQL__INTERFACE__DATABASE,
	UPDATE__RELATIONSHIP__MUTATION__GRAPHQL__INTERFACE__DATABASE,
	DELETE__RELATIONSHIP__MUTATION__GRAPHQL__INTERFACE__DATABASE,
} from "./../mutations/relationship.js";

const CONNECTION__RELATIONSHIP__ENTITY__GRAPHQL__INTERFACE__DATABASE = {
	query_relationships: $structure.entities.relationship.database.graphql.QUERY_RELATIONSHIPS_FIELDS__GRAPHQL__DATABASE__RELATIONSHIP__STRUCTURE,
	mutation_relationships: $structure.entities.relationship.database.graphql.MUTATION_RELATIONSHIPS_FIELDS__GRAPHQL__DATABASE__RELATIONSHIP__STRUCTURE,
	query_query: $structure.entities.relationship.database.graphql.QUERY_QUERY_FIELDS__GRAPHQL__DATABASE__RELATIONSHIP__STRUCTURE,
	mutation_mutation: $structure.entities.relationship.database.graphql.MUTATION_MUTATION_FIELDS__GRAPHQL__DATABASE__RELATIONSHIP__STRUCTURE,
};

const METHODS__RELATIONSHIP__ENTITY__GRAPHQL__INTERFACE__DATABASE = {
	query: {
		read_relationship: READ__RELATIONSHIP__QUERY__GRAPHQL__INTERFACE__DATABASE,
		count_relationship: COUNT__RELATIONSHIP__QUERY__GRAPHQL__INTERFACE__DATABASE,
	},
	mutation: {
		create_relationship: CREATE__RELATIONSHIP__MUTATION__GRAPHQL__INTERFACE__DATABASE,
		update_relationship: UPDATE__RELATIONSHIP__MUTATION__GRAPHQL__INTERFACE__DATABASE,
		delete_relationship: DELETE__RELATIONSHIP__MUTATION__GRAPHQL__INTERFACE__DATABASE,
	},
};

export { CONNECTION__RELATIONSHIP__ENTITY__GRAPHQL__INTERFACE__DATABASE, METHODS__RELATIONSHIP__ENTITY__GRAPHQL__INTERFACE__DATABASE };
