import fs from "fs";
import path from "path";

const CREATE_NAME__GAUZE__OPERATION__GRAPHQL__INTERFACE__DATABASE = "CreateGauze";
const CREATE__GAUZE__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./create.graphql"), {
	encoding: "utf8",
});
const READ_NAME__GAUZE__OPERATION__GRAPHQL__INTERFACE__DATABASE = "ReadGauze";
const READ__GAUZE__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./read.graphql"), {
	encoding: "utf8",
});
const UPDATE_NAME__GAUZE__OPERATION__GRAPHQL__INTERFACE__DATABASE = "UpdateGauze";
const UPDATE__GAUZE__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./update.graphql"), {
	encoding: "utf8",
});
const DELETE_NAME__GAUZE__OPERATION__GRAPHQL__INTERFACE__DATABASE = "DeleteGauze";
const DELETE__GAUZE__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./delete.graphql"), {
	encoding: "utf8",
});
const COUNT_NAME__GAUZE__OPERATION__GRAPHQL__INTERFACE__DATABASE = "CountGauze";
const COUNT__GAUZE__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./count.graphql"), {
	encoding: "utf8",
});

export {
	CREATE_NAME__GAUZE__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	CREATE__GAUZE__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	READ_NAME__GAUZE__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	READ__GAUZE__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	UPDATE_NAME__GAUZE__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	UPDATE__GAUZE__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	DELETE_NAME__GAUZE__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	DELETE__GAUZE__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	COUNT_NAME__GAUZE__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	COUNT__GAUZE__OPERATION__GRAPHQL__INTERFACE__DATABASE,
};
