import fs from "fs";
import path from "path";

const CREATE_NAME__AGENT_ACCOUNT__OPERATION__GRAPHQL__INTERFACE__DATABASE = "CreateAgent_Account";
const CREATE__AGENT_ACCOUNT__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./create.graphql"), {
	encoding: "utf8",
});
const READ_NAME__AGENT_ACCOUNT__OPERATION__GRAPHQL__INTERFACE__DATABASE = "ReadAgent_Account";
const READ__AGENT_ACCOUNT__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./read.graphql"), {
	encoding: "utf8",
});
const UPDATE_NAME__AGENT_ACCOUNT__OPERATION__GRAPHQL__INTERFACE__DATABASE = "UpdateAgent_Account";
const UPDATE__AGENT_ACCOUNT__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./update.graphql"), {
	encoding: "utf8",
});
const DELETE_NAME__AGENT_ACCOUNT__OPERATION__GRAPHQL__INTERFACE__DATABASE = "DeleteAgent_Account";
const DELETE__AGENT_ACCOUNT__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./delete.graphql"), {
	encoding: "utf8",
});
const COUNT_NAME__AGENT_ACCOUNT__OPERATION__GRAPHQL__INTERFACE__DATABASE = "CountAgent_Account";
const COUNT__AGENT_ACCOUNT__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./count.graphql"), {
	encoding: "utf8",
});

export {
	CREATE_NAME__AGENT_ACCOUNT__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	CREATE__AGENT_ACCOUNT__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	READ_NAME__AGENT_ACCOUNT__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	READ__AGENT_ACCOUNT__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	UPDATE_NAME__AGENT_ACCOUNT__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	UPDATE__AGENT_ACCOUNT__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	DELETE_NAME__AGENT_ACCOUNT__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	DELETE__AGENT_ACCOUNT__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	COUNT_NAME__AGENT_ACCOUNT__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	COUNT__AGENT_ACCOUNT__OPERATION__GRAPHQL__INTERFACE__DATABASE,
};
