import * as $kernel from "./../../kernel/index.js";

import { RELATIONSHIP_MODEL_DATABASE } from "./../models/relationship.js";

const RELATIONSHIP_CONTROLLER_ROOT_CONFIG = {};
const RELATIONSHIP_CONTROLLER_DATABASE_CONFIG = {
	model: RELATIONSHIP_MODEL_DATABASE,
	model_name: "RELATIONSHIP_MODEL_DATABASE",
};
const RELATIONSHIP_CONTROLLER_DATABASE = new $kernel.controllers.database.DatabaseController(RELATIONSHIP_CONTROLLER_ROOT_CONFIG, RELATIONSHIP_CONTROLLER_DATABASE_CONFIG);

export { RELATIONSHIP_CONTROLLER_DATABASE };
