import { TYPE__GRAPHQL__DATABASE__ENTITY1__STRUCTURE } from "./entity1/database/graphql.js";
import { TABLE_NAME__SQL__DATABASE__ENTITY1__STRUCTURE } from "./entity1/database/sql.js";

function invert(obj) {
	const inverted = {};
	Object.keys(obj).forEach(function (key) {
		const val = obj[key];
		inverted[val] = key;
	});
	return inverted;
}

const DATABASE_GRAPHQL_TYPE_TO_SQL_TABLE = {
	[TYPE__GRAPHQL__DATABASE__ENTITY1__STRUCTURE]: TABLE_NAME__SQL__DATABASE__ENTITY1__STRUCTURE,
};
const DATABASE_SQL_TABLE_TO_GRAPHQL_TYPE = invert(DATABASE_GRAPHQL_TYPE_TO_SQL_TABLE);

const SYSTEM_GRAPHQL_TYPE_TO_SQL_TABLE = DATABASE_GRAPHQL_TYPE_TO_SQL_TABLE;
const SYSTEM_SQL_TABLE_TO_GRAPHQL_TYPE = DATABASE_SQL_TABLE_TO_GRAPHQL_TYPE;

export { DATABASE_GRAPHQL_TYPE_TO_SQL_TABLE, DATABASE_SQL_TABLE_TO_GRAPHQL_TYPE, SYSTEM_GRAPHQL_TYPE_TO_SQL_TABLE, SYSTEM_SQL_TABLE_TO_GRAPHQL_TYPE };
