#!/bin/zsh

if [ $# -eq 0 ]
  then
    echo "No arguments supplied"
	exit 1
fi

arg1="$1"
echo "arg1: $arg1"
arg2=$(echo "$arg1" | node to_upper.js)
echo "arg2: $arg2"
arg3=${arg1:u}
echo "arg3: $arg3"

mkdir -p ./$1

mkdir -p ./$1/structure
mkdir -p ./$1/database
mkdir -p ./$1/system

cp -r ./base_gauze/structure/* ./$1/structure/
cp -r ./base_gauze/database/* ./$1/database/
cp -r ./base_gauze/system/* ./$1/system/

find $1 -type f -name '*.js' -exec sed -i '' 's/a543731262804f64adcc0eae1a225acc/'$arg1'/g' {} +
find $1 -type f -name '*.js' -exec sed -i '' 's/bb95d174a16f4ddd935ff3a802f7c7bc/'$arg2'/g' {} +
find $1 -type f -name '*.js' -exec sed -i '' 's/caf5342ac38d41a6a02bb81d2d2b21a4/'$arg3'/g' {} +

find $1 -type f -name '*.graphql' -exec sed -i '' 's/a543731262804f64adcc0eae1a225acc/'$arg1'/g' {} +
find $1 -type f -name '*.graphql' -exec sed -i '' 's/bb95d174a16f4ddd935ff3a802f7c7bc/'$arg2'/g' {} +
find $1 -type f -name '*.graphql' -exec sed -i '' 's/caf5342ac38d41a6a02bb81d2d2b21a4/'$arg3'/g' {} +

