import fs from "fs";
import path from "path";

const CREATE_NAME__SECRET__OPERATION__GRAPHQL__INTERFACE__DATABASE = "CreateSecret";
const CREATE__SECRET__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./create.graphql"), {
	encoding: "utf8",
});
const READ_NAME__SECRET__OPERATION__GRAPHQL__INTERFACE__DATABASE = "ReadSecret";
const READ__SECRET__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./read.graphql"), {
	encoding: "utf8",
});
const UPDATE_NAME__SECRET__OPERATION__GRAPHQL__INTERFACE__DATABASE = "UpdateSecret";
const UPDATE__SECRET__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./update.graphql"), {
	encoding: "utf8",
});
const DELETE_NAME__SECRET__OPERATION__GRAPHQL__INTERFACE__DATABASE = "DeleteSecret";
const DELETE__SECRET__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./delete.graphql"), {
	encoding: "utf8",
});

export {
	CREATE_NAME__SECRET__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	CREATE__SECRET__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	READ_NAME__SECRET__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	READ__SECRET__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	UPDATE_NAME__SECRET__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	UPDATE__SECRET__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	DELETE_NAME__SECRET__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	DELETE__SECRET__OPERATION__GRAPHQL__INTERFACE__DATABASE,
};
