import fs from "fs";
import path from "path";

const CREATE_NAME__AGENT_PERSON__OPERATION__GRAPHQL__INTERFACE__DATABASE = "CreateAgent_Person";
const CREATE__AGENT_PERSON__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./create.graphql"), {
	encoding: "utf8",
});
const READ_NAME__AGENT_PERSON__OPERATION__GRAPHQL__INTERFACE__DATABASE = "ReadAgent_Person";
const READ__AGENT_PERSON__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./read.graphql"), {
	encoding: "utf8",
});
const CURSOR_READ_NAME__AGENT_PERSON__OPERATION__GRAPHQL__INTERFACE__DATABASE = "CursorReadAgent_Person";
const CURSOR_READ__AGENT_PERSON__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./cursor_read.graphql"), {
	encoding: "utf8",
});
const UPDATE_NAME__AGENT_PERSON__OPERATION__GRAPHQL__INTERFACE__DATABASE = "UpdateAgent_Person";
const UPDATE__AGENT_PERSON__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./update.graphql"), {
	encoding: "utf8",
});
const CURSOR_UPDATE_NAME__AGENT_PERSON__OPERATION__GRAPHQL__INTERFACE__DATABASE = "CursorUpdateAgent_Person";
const CURSOR_UPDATE__AGENT_PERSON__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./cursor_update.graphql"), {
	encoding: "utf8",
});
const DELETE_NAME__AGENT_PERSON__OPERATION__GRAPHQL__INTERFACE__DATABASE = "DeleteAgent_Person";
const DELETE__AGENT_PERSON__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./delete.graphql"), {
	encoding: "utf8",
});
const CURSOR_DELETE_NAME__AGENT_PERSON__OPERATION__GRAPHQL__INTERFACE__DATABASE = "CursorDeleteAgent_Person";
const CURSOR_DELETE__AGENT_PERSON__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./cursor_delete.graphql"), {
	encoding: "utf8",
});
const COUNT_NAME__AGENT_PERSON__OPERATION__GRAPHQL__INTERFACE__DATABASE = "CountAgent_Person";
const COUNT__AGENT_PERSON__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./count.graphql"), {
	encoding: "utf8",
});

export {
	CREATE_NAME__AGENT_PERSON__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	CREATE__AGENT_PERSON__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	READ_NAME__AGENT_PERSON__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	READ__AGENT_PERSON__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	CURSOR_READ_NAME__AGENT_PERSON__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	CURSOR_READ__AGENT_PERSON__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	UPDATE_NAME__AGENT_PERSON__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	UPDATE__AGENT_PERSON__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	CURSOR_UPDATE_NAME__AGENT_PERSON__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	CURSOR_UPDATE__AGENT_PERSON__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	DELETE_NAME__AGENT_PERSON__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	DELETE__AGENT_PERSON__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	CURSOR_DELETE_NAME__AGENT_PERSON__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	CURSOR_DELETE__AGENT_PERSON__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	COUNT_NAME__AGENT_PERSON__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	COUNT__AGENT_PERSON__OPERATION__GRAPHQL__INTERFACE__DATABASE,
};
