// relationships are defined using the graphql type constant

import {
	GRAPHQL_DATABASE_ENTITY1_TYPE_STRUCTURE
} from './entity1/database/graphql.js'
import {
	GRAPHQL_DATABASE_ENTITY2_TYPE_STRUCTURE
} from './entity2/database/graphql.js'

const DATABASE_RELATIONSHIP_STRUCTURE = {
	[GRAPHQL_DATABASE_ENTITY1_TYPE_STRUCTURE]: [GRAPHQL_DATABASE_ENTITY2_TYPE_STRUCTURE],
	[GRAPHQL_DATABASE_ENTITY2_TYPE_STRUCTURE]: [GRAPHQL_DATABASE_ENTITY1_TYPE_STRUCTURE]
}

const SYSTEM_RELATIONSHIP_STRUCTURE = DATABASE_RELATIONSHIP_STRUCTURE

export {
	DATABASE_RELATIONSHIP_STRUCTURE,
	SYSTEM_RELATIONSHIP_STRUCTURE
}