// relationships are defined using the graphql type constant

// ytitne
import { TYPE__GRAPHQL__DATABASE__YTITNE__STRUCTURE } from "./entities/ytitne/database/graphql.js";
// entity
import { TYPE__GRAPHQL__DATABASE__ENTITY__STRUCTURE } from "./entities/entity/database/graphql.js";

/*
	ytitne <-> ytitne
	ytitne <-> entity
*/
const DATABASE__RELATIONSHIP__STRUCTURE = {
	[TYPE__GRAPHQL__DATABASE__YTITNE__STRUCTURE]: [TYPE__GRAPHQL__DATABASE__YTITNE__STRUCTURE, TYPE__GRAPHQL__DATABASE__ENTITY__STRUCTURE],
	[TYPE__GRAPHQL__DATABASE__ENTITY__STRUCTURE]: [TYPE__GRAPHQL__DATABASE__ENTITY__STRUCTURE, TYPE__GRAPHQL__DATABASE__YTITNE__STRUCTURE],
};

const SYSTEM__RELATIONSHIP__STRUCTURE = DATABASE__RELATIONSHIP__STRUCTURE;

export { DATABASE__RELATIONSHIP__STRUCTURE, SYSTEM__RELATIONSHIP__STRUCTURE };
