import {
	GRAPHQL_DATABASE_ENTITY1_TYPE_STRUCTURE
} from './entity1/database/graphql.js'
import {
	SQL_DATABASE_ENTITY1_TABLE_NAME
} from './entity1/database/sql.js'
import {
	GRAPHQL_DATABASE_ENTITY2_TYPE_STRUCTURE
} from './entity2/database/graphql.js'
import {
	SQL_DATABASE_ENTITY2_TABLE_NAME
} from './entity2/database/sql.js'

function invert (obj) {
	const inverted = {}
	Object.keys(obj).forEach(function (key) {
		const val = obj[key]
		inverted[val] = key
	})
	return inverted
}

const DATABASE_GRAPHQL_TYPE_TO_SQL_TABLE = {
	[GRAPHQL_DATABASE_ENTITY1_TYPE_STRUCTURE]: SQL_DATABASE_ENTITY1_TABLE_NAME,
	[GRAPHQL_DATABASE_ENTITY2_TYPE_STRUCTURE]: SQL_DATABASE_ENTITY2_TABLE_NAME
}
const DATABASE_SQL_TABLE_TO_GRAPHQL_TYPE = invert(DATABASE_GRAPHQL_TYPE_TO_SQL_TABLE)

const SYSTEM_GRAPHQL_TYPE_TO_SQL_TABLE = DATABASE_GRAPHQL_TYPE_TO_SQL_TABLE
const SYSTEM_SQL_TABLE_TO_GRAPHQL_TYPE = DATABASE_SQL_TABLE_TO_GRAPHQL_TYPE

export {
	DATABASE_GRAPHQL_TYPE_TO_SQL_TABLE,
	DATABASE_SQL_TABLE_TO_GRAPHQL_TYPE,
	SYSTEM_GRAPHQL_TYPE_TO_SQL_TABLE,
	SYSTEM_SQL_TABLE_TO_GRAPHQL_TYPE
}