import fs from "fs";
import path from "path";

const CREATE_NAME__ENTITY__OPERATION__GRAPHQL__INTERFACE__DATABASE = "CreateEntity";
const CREATE__ENTITY__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./create.graphql"), {
	encoding: "utf8",
});
const READ_NAME__ENTITY__OPERATION__GRAPHQL__INTERFACE__DATABASE = "ReadEntity";
const READ__ENTITY__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./read.graphql"), {
	encoding: "utf8",
});
const CURSOR_READ_NAME__ENTITY__OPERATION__GRAPHQL__INTERFACE__DATABASE = "CursorReadEntity";
const CURSOR_READ__ENTITY__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./cursor_read.graphql"), {
	encoding: "utf8",
});
const UPDATE_NAME__ENTITY__OPERATION__GRAPHQL__INTERFACE__DATABASE = "UpdateEntity";
const UPDATE__ENTITY__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./update.graphql"), {
	encoding: "utf8",
});
const CURSOR_UPDATE_NAME__ENTITY__OPERATION__GRAPHQL__INTERFACE__DATABASE = "CursorUpdateEntity";
const CURSOR_UPDATE__ENTITY__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./cursor_update.graphql"), {
	encoding: "utf8",
});
const DELETE_NAME__ENTITY__OPERATION__GRAPHQL__INTERFACE__DATABASE = "DeleteEntity";
const DELETE__ENTITY__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./delete.graphql"), {
	encoding: "utf8",
});
const CURSOR_DELETE_NAME__ENTITY__OPERATION__GRAPHQL__INTERFACE__DATABASE = "CursorDeleteEntity";
const CURSOR_DELETE__ENTITY__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./cursor_delete.graphql"), {
	encoding: "utf8",
});
const COUNT_NAME__ENTITY__OPERATION__GRAPHQL__INTERFACE__DATABASE = "CountEntity";
const COUNT__ENTITY__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./count.graphql"), {
	encoding: "utf8",
});

export {
	CREATE_NAME__ENTITY__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	CREATE__ENTITY__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	READ_NAME__ENTITY__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	READ__ENTITY__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	CURSOR_READ_NAME__ENTITY__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	CURSOR_READ__ENTITY__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	UPDATE_NAME__ENTITY__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	UPDATE__ENTITY__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	CURSOR_UPDATE_NAME__ENTITY__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	CURSOR_UPDATE__ENTITY__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	DELETE_NAME__ENTITY__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	DELETE__ENTITY__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	CURSOR_DELETE_NAME__ENTITY__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	CURSOR_DELETE__ENTITY__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	COUNT_NAME__ENTITY__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	COUNT__ENTITY__OPERATION__GRAPHQL__INTERFACE__DATABASE,
};
