import fs from 'fs'
import path from 'path'

const ENTITY1_CREATE_OPERATION_NAME_GRAPHQL_INTERFACE_DATABASE = 'CreateEntity1'
const ENTITY1_CREATE_OPERATION_GRAPHQL_INTERFACE_DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, './create.graphql'), {
	encoding: 'utf8'
})
const ENTITY1_READ_OPERATION_NAME_GRAPHQL_INTERFACE_DATABASE = 'ReadEntity1'
const ENTITY1_READ_OPERATION_GRAPHQL_INTERFACE_DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, './read.graphql'), {
	encoding: 'utf8'
})
const ENTITY1_UPDATE_OPERATION_NAME_GRAPHQL_INTERFACE_DATABASE = 'UpdateEntity1'
const ENTITY1_UPDATE_OPERATION_GRAPHQL_INTERFACE_DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, './update.graphql'), {
	encoding: 'utf8'
})
const ENTITY1_DELETE_OPERATION_NAME_GRAPHQL_INTERFACE_DATABASE = 'DeleteEntity1'
const ENTITY1_DELETE_OPERATION_GRAPHQL_INTERFACE_DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, './delete.graphql'), {
	encoding: 'utf8'
})

export {
	ENTITY1_CREATE_OPERATION_NAME_GRAPHQL_INTERFACE_DATABASE,
	ENTITY1_CREATE_OPERATION_GRAPHQL_INTERFACE_DATABASE,
	ENTITY1_READ_OPERATION_NAME_GRAPHQL_INTERFACE_DATABASE,
	ENTITY1_READ_OPERATION_GRAPHQL_INTERFACE_DATABASE,
	ENTITY1_UPDATE_OPERATION_NAME_GRAPHQL_INTERFACE_DATABASE,
	ENTITY1_UPDATE_OPERATION_GRAPHQL_INTERFACE_DATABASE,
	ENTITY1_DELETE_OPERATION_NAME_GRAPHQL_INTERFACE_DATABASE,
	ENTITY1_DELETE_OPERATION_GRAPHQL_INTERFACE_DATABASE
}