import fs from "fs";
import path from "path";

const CREATE_NAME__AGENT_USER__OPERATION__GRAPHQL__INTERFACE__DATABASE = "CreateAgent_User";
const CREATE__AGENT_USER__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./create.graphql"), {
	encoding: "utf8",
});
const READ_NAME__AGENT_USER__OPERATION__GRAPHQL__INTERFACE__DATABASE = "ReadAgent_User";
const READ__AGENT_USER__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./read.graphql"), {
	encoding: "utf8",
});
const UPDATE_NAME__AGENT_USER__OPERATION__GRAPHQL__INTERFACE__DATABASE = "UpdateAgent_User";
const UPDATE__AGENT_USER__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./update.graphql"), {
	encoding: "utf8",
});
const DELETE_NAME__AGENT_USER__OPERATION__GRAPHQL__INTERFACE__DATABASE = "DeleteAgent_User";
const DELETE__AGENT_USER__OPERATION__GRAPHQL__INTERFACE__DATABASE = fs.readFileSync(path.resolve(import.meta.dirname, "./delete.graphql"), {
	encoding: "utf8",
});

export {
	CREATE_NAME__AGENT_USER__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	CREATE__AGENT_USER__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	READ_NAME__AGENT_USER__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	READ__AGENT_USER__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	UPDATE_NAME__AGENT_USER__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	UPDATE__AGENT_USER__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	DELETE_NAME__AGENT_USER__OPERATION__GRAPHQL__INTERFACE__DATABASE,
	DELETE__AGENT_USER__OPERATION__GRAPHQL__INTERFACE__DATABASE,
};
