const SQL_DATABASE_RELATIONSHIP_TABLE_NAME = 'gauze__relationship'
const SQL_DATABASE_RELATIONSHIP_PRIMARY_KEY = '_id'

export {
	SQL_DATABASE_RELATIONSHIP_TABLE_NAME,
	SQL_DATABASE_RELATIONSHIP_PRIMARY_KEY
}