import {
	SERIALIZER_CREATED_AT_STRUCTURE,
	SERIALIZER_UPDATED_AT_STRUCTURE,
	SERIALIZER_DELETED_AT_STRUCTURE
} from './../../serializers.js'

const TABLE_NAME__SQL__DATABASE__RELATIONSHIP__STRUCTURE = 'gauze__relationship'
const PRIMARY_KEY__SQL__DATABASE__RELATIONSHIP__STRUCTURE = '_id'
const FIELDS__SQL__DATABASE__RELATIONSHIP__STRUCTURE = {
	_id: true,
	_created_at: true,
	_updated_at: true,
	_deleted_at: true,
	_from_type: true,
	_from_id: true,
	_to_type: true,
	_to_id: true
}
const PROTECTED_FIELDS__SQL__DATABASE__RELATIONSHIP__STRUCTURE = ['_id', '_created_at', '_updated_at', '_deleted_at']
const FIELD_SERIALIZERS__SQL__DATABASE__RELATIONSHIP__STRUCTURE = {
	_created_at: SERIALIZER_CREATED_AT_STRUCTURE('_created_at'),
	_updated_at: SERIALIZER_UPDATED_AT_STRUCTURE('_updated_at'),
	_deleted_at: SERIALIZER_DELETED_AT_STRUCTURE('_deleted_at')
}

export {
	TABLE_NAME__SQL__DATABASE__RELATIONSHIP__STRUCTURE,
	PRIMARY_KEY__SQL__DATABASE__RELATIONSHIP__STRUCTURE,
	FIELDS__SQL__DATABASE__RELATIONSHIP__STRUCTURE,
	PROTECTED_FIELDS__SQL__DATABASE__RELATIONSHIP__STRUCTURE,
	FIELD_SERIALIZERS__SQL__DATABASE__RELATIONSHIP__STRUCTURE
}
