// relationships are defined using the graphql type constant

// ytitne
import { TYPE__GRAPHQL__DATABASE__YTITNE__STRUCTURE } from "./ytitne/database/graphql.js";
// entity1
import { TYPE__GRAPHQL__DATABASE__ENTITY__STRUCTURE } from "./entity/database/graphql.js";

/*
	ytitne <-> entity1
*/
const DATABASE_RELATIONSHIP_STRUCTURE = {
	[TYPE__GRAPHQL__DATABASE__YTITNE__STRUCTURE]: [TYPE__GRAPHQL__DATABASE__YTITNE__STRUCTURE, TYPE__GRAPHQL__DATABASE__ENTITY__STRUCTURE],
	[TYPE__GRAPHQL__DATABASE__ENTITY__STRUCTURE]: [TYPE__GRAPHQL__DATABASE__YTITNE__STRUCTURE],
};

const SYSTEM_RELATIONSHIP_STRUCTURE = DATABASE_RELATIONSHIP_STRUCTURE;

export { DATABASE_RELATIONSHIP_STRUCTURE, SYSTEM_RELATIONSHIP_STRUCTURE };
